#端口9999
server:
  port: 9999
spring:
  # 应用名称
  application:
    name: Talent-management-back
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库地址
    url: jdbc:mysql://106.14.145.85:3306/management_system?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    #数据库用户名
    username: root
    #数据库密码
    password: 123123
    #全局规定json date数据格式
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  #验证码发送邮箱配置
  mail:
    host: smtp.163.com
    username: talent_management@163.com
    password: SCJWCNWTGKFLMPUX
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#配置验证码邮件发送方
mail:
  fromMail:
    addr: talent_management@163.com

# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认名称是类名）
  type-aliases-package: com.foe.talentmanagementback.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true


#Mybatis SQL语句，控制台输出
logging:
  level:
    com.foe.talentmanagementback.mapper: debug
    root: info

